
running: true
interval: 1 # in minutes
raindrop_tag: 'post-to-twitter'
tweet_format: '{title:.100}\n{url}' #.100 is truncation, follows the rules of python string formatting: https://pyformat.info/
default_image_url: 'https://www.dropbox.com/s/97g0fror3egbq9w/v3%20demo.jpg?dl=0'

