
## see detailed instructions at https://github.com/nwspk/lcpt_twitter_bot#how-to-configure

# boolean, true or false, turns the bot on and off
running: true

# in minutes, the tweeting interval. Minimum is every 5 minutes; Bot won't take into account a tweeting interval shorter than the polling interval (5min)
interval: 20

raindrop_tag: 'post-to-twitter'

tweet_format: '{title:.60}\n{description:.195}\n{url}'

default_image_url: 'https://www.dropbox.com/s/97g0fror3egbq9w/v3%20demo.jpg?dl=0'

