
name: continuous_integration
on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check out the source
        run: ssh staging 'cd ~/lcpt_twitter_bot && git pull'

      - name: Start the bot
        run: ssh staging 'cd ~/lcpt_twitter_bot && python3 run.py'
        env:
          RAINDROP_CLIENT_ID: ${{ secrets.RAINDROP_CLIENT_ID }}
          RAINDROP_CLIENT_SECRET: ${{ secrets.RAINDROP_CLIENT_SECRET }}
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
          TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
          TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

